// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PressfordConsultingApi.Repository;

namespace PressfordConsultingApi.Migrations
{
    [DbContext(typeof(PressfordConsultingDbContext))]
    [Migration("20210215122100_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PressfordConsultingApi.Models.Article", b =>
                {
                    b.Property<int>("articleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("articleBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("articleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("articleName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("articleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("likes")
                        .HasColumnType("int");

                    b.HasKey("articleId");

                    b.ToTable("Article");
                });
#pragma warning restore 612, 618
        }
    }
}
